# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mnn-5LyYFd_foW8aezCtrQmaYL-n8DZs
"""

import socket
from protocol import unpack_offer, pack_request, UDP_PORT

class GameClient:
    def __init__(self):
        self.team_name = "HilaAndYarden"
        print("Client started, listening for offer requests...")

    def listen_for_offers(self):
        # יצירת סוקט UDP להאזנה
        udp_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        udp_socket.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
        udp_socket.bind(('', UDP_PORT))

        try:
            # מחכים להודעת הצעה אחת
            data, addr = udp_socket.recvfrom(1024)
            result = unpack_offer(data)

            if result:
                server_port, server_name = result
                print(f"Received offer from {server_name} at address {addr[0]}, attempting to connect...")

                # ברגע שנמצא שרת, מתחברים אליו ב-TCP
                self.connect_to_server(addr[0], server_port)
        except Exception as e:
            print(f"Error: {e}")
        finally:
            udp_socket.close()

    def connect_to_server(self, server_ip, server_port):
        try:
            tcp_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
            tcp_socket.connect((server_ip, server_port))
            print("Connected to server!")

            # קלט מהמשתמש
            try:
                rounds = int(input("How many rounds you want to play? "))
            except:
                rounds = 1 # ברירת מחדל

            # שליחת הבקשה
            packet = pack_request(rounds, self.team_name)
            tcp_socket.sendall(packet)

            print(f"Sent request for {rounds} rounds. Waiting for game...")

            # כאן הלקוח יחכה לתשובות מהמשחק בהמשך

        except Exception as e:
            print(f"Failed to connect: {e}")

if __name__ == "__main__":
    GameClient().listen_for_offers()

