# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mnn-5LyYFd_foW8aezCtrQmaYL-n8DZs
"""

import struct

MAGIC_COOKIE = 0xabcddcba
MSG_TYPE_OFFER = 0x02
MSG_TYPE_REQUEST = 0x03
MSG_TYPE_PAYLOAD = 0x04
UDP_PORT = 13117

def pack_offer(server_port, server_name):
    """אריזת הודעת UDP מהשרת (Magic Cookie + Type + Port + Name)"""
    # מוודאים שהשם הוא בדיוק 32 תווים (מרפדים באפסים אם צריך)
    server_name_bytes = server_name.encode('utf-8')[:32].ljust(32, b'\x00')
    return struct.pack('>IBH32s', MAGIC_COOKIE, MSG_TYPE_OFFER, server_port, server_name_bytes)

def unpack_offer(data):
    """פתיחת הודעת UDP בלקוח"""
    if len(data) < 39: return None
    try:
        cookie, msg_type, server_port, server_name_bytes = struct.unpack('>IBH32s', data[:39])
        if cookie != MAGIC_COOKIE or msg_type != MSG_TYPE_OFFER: return None
        return server_port, server_name_bytes.decode('utf-8').rstrip('\x00')
    except: return None

def pack_request(num_rounds, team_name):
    """אריזת הודעת בקשה מהלקוח (Magic Cookie + Type + Rounds + TeamName)"""
    team_name_bytes = team_name.encode('utf-8')[:32].ljust(32, b'\x00')
    return struct.pack('>IBB32s', MAGIC_COOKIE, MSG_TYPE_REQUEST, num_rounds, team_name_bytes)

def unpack_request(data):
    """פתיחת הודעת בקשה בשרת"""
    if len(data) < 38: return None
    try:
        cookie, msg_type, num_rounds, team_name_bytes = struct.unpack('>IBB32s', data[:38])
        if cookie != MAGIC_COOKIE or msg_type != MSG_TYPE_REQUEST: return None
        return num_rounds, team_name_bytes.decode('utf-8').rstrip('\x00')
    except: return None

