# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mnn-5LyYFd_foW8aezCtrQmaYL-n8DZs
"""

import socket
import time
import threading
from protocol import pack_offer, unpack_request, UDP_PORT

class GameServer:
    def __init__(self, port=0):
        # יצירת סוקט TCP
        self.tcp_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.tcp_socket.bind(('', port))
        self.tcp_socket.listen()
        self.tcp_port = self.tcp_socket.getsockname()[1]

        self.server_name = "HilaAndYarden"

        # מציאת כתובת ה-IP המקומית לשידור
        try:
            self.ip_address = socket.gethostbyname(socket.gethostname())
        except:
            self.ip_address = "127.0.0.1"

        print(f"Server started, listening on IP address {self.ip_address}")

    def broadcast_offers(self):
        """שידור הצעות ב-UDP כל שנייה"""
        udp_socket = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        udp_socket.setsockopt(socket.SOL_SOCKET, socket.SO_BROADCAST, 1)
        packet = pack_offer(self.tcp_port, self.server_name)

        while True:
            udp_socket.sendto(packet, ('<broadcast>', UDP_PORT))
            time.sleep(1)

    def handle_client(self, client_socket, addr):
        """טיפול בלקוח שהתחבר"""
        print(f"Connection accepted from {addr}")
        try:
            # שלב 1: קבלת הודעת Request
            data = client_socket.recv(1024)
            request = unpack_request(data)

            if request:
                num_rounds, team_name = request
                print(f"Team '{team_name}' wants to play {num_rounds} rounds.")

                # כאן תיכנס לוגיקת המשחק בהמשך
                # כרגע השרת רק מאשר את החיבור ומסיים
            else:
                print("Invalid request received.")

        except Exception as e:
            print(f"Error handling client: {e}")
        finally:
            client_socket.close()
            print(f"Connection closed for {addr}")

    def start(self):
        # הפעלת שידורי UDP ברקע
        threading.Thread(target=self.broadcast_offers, daemon=True).start()

        # לולאה ראשית שמחכה לחיבורי TCP
        while True:
            client_socket, addr = self.tcp_socket.accept()
            # טיפול בכל לקוח ב-Thread נפרד
            threading.Thread(target=self.handle_client, args=(client_socket, addr)).start()

if __name__ == "__main__":
    GameServer().start()

